exports.WEEKDAY_OFFSET = {
    'zondag': 0,
    'zo': 0,
    'zon': 0,
    'maandag': 1,
    'ma': 1,
    'dinsdag': 2,
    'di':2,
    'di': 2,
    'woensdag': 3,
    'woe': 3,
    'donderdag': 4,
    'do': 4,
    'don': 4,
    'vrijdag': 5,
    'vrij': 5,
    'zaterdag': 6,
    'zat': 6,
    'za': 6
}

exports.MONTH_OFFSET = {
    'januari': 1,
    'ja': 1,
    'jan': 1,
    'jan.': 1,
    'februari': 2,
    'feb': 2,
    'feb.': 2,
    'maart': 3,
    'ma': 3,
    'ma.': 3,
    'maa': 3,
    'maa.': 3,
    'april': 4,
    'apr': 4,
    'apr.': 4,
    'mei': 5,
    'juni': 6,
    'jun': 6,
    'jun.': 6,
    'juli': 7,
    'jul': 7,
    'jul.': 7,
    'augustus': 8,
    'aug': 8,
    'aug.': 8,
    'september': 9,
    'sep': 9,
    'sep.': 9,
    'sept': 9,
    'sept.': 9,
    'oktober': 10,
    'oct': 10,
    'oct.': 10,
    'november': 11,
    'nov': 11,
    'nov.': 11,
    'december': 12,
    'dec': 12,
    'dec.': 12,
}

exports.NUMBERS = {
    'één': 1,
    'een': 1,
    'twee': 2,
    'drie': 3,
    'vier': 4,
    'tien': 10,
    'twintig': 20,
    'vijftien': 15,
    'dertig': 30,
    'veertig': 40,
    'vijftig': 50
}